version: '3.2'
services:
    script-runner:
        build:
            context: ./script-runner
        volumes:
            -   .:/volume
    config-provider:
        build:
            context: ./config-provider
        ports:
            -   "5050:443"
        volumes:
            -   ./storage/config-provider/ssl:/etc/nginx/ssl
            -   ./storage/config-provider/scripts:/srv/flask_app/config
            -   ./scripts/wait-for-script-runner.sh:/tmp/wait-for-script-runner.sh
        depends_on:
            -   script-runner
        command: ["/tmp/wait-for-script-runner.sh", "script-runner", "./start.sh"]

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
            -   "9200:9200"
            -   "9300:9300"
        volumes:
            -   ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            -   ./storage/elasticsearch/ssl:/usr/share/elasticsearch/config/certs
            -   ./scripts/wait-for-script-runner.sh:/tmp/wait-for-script-runner.sh
        environment:
            discovery.type: single-node
            ELASTIC_PASSWORD: tfgelastic1920
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
            -   script-runner
        command: ["/tmp/wait-for-script-runner.sh", "script-runner", "/usr/local/bin/docker-entrypoint.sh"]

    logstash:
            #image: docker.elastic.co/logstash/logstash:7.6.2
        build:
            context: ./logstash
        ports:
            -   "9600:9600"
            -   "10514:10514"
        volumes:
            -   ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            -   ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
            -   ./storage/logstash/ssl:/usr/share/logstash/config/certs
            -   ./scripts/wait-for-script-runner.sh:/tmp/wait-for-script-runner.sh
        depends_on:
            -   elasticsearch
            -   script-runner
        command: ["/tmp/wait-for-script-runner.sh", "script-runner", "/usr/local/bin/docker-entrypoint"]
    

    kibana:
            #image: docker.elastic.co/kibana/kibana:7.6.2
        build:
            context: ./kibana
        ports:
            -   "5601:5601"
        volumes:
            -   ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
            -   ./storage/kibana/ssl:/usr/share/kibana/config/certs
            -   ./scripts/wait-for-script-runner.sh:/tmp/wait-for-script-runner.sh
        depends_on:
            -   elasticsearch
            -   script-runner
        command: ["/tmp/wait-for-script-runner.sh", "script-runner", "/usr/local/bin/kibana-docker"]
